### ISSUE TITLE
[Issue] Automatic modpack installer fails when user runs out of disk space.

### ISSUE THREAD

**Issue by Crutionix** [RyanWalpoleEnterprises/Stardew-Valley-Mod-Manager#6]
**Issue:** 
When the user runs out of disk space when installing a modpack, the mods will be partially installed up until the point that the drive runs out of space. The program will then throw exceptions about file and folder access.

**Steps to Replicate:**
1. Have no disk space on drive where Stardew Valley directory is stored.
2. Download modpack with automatic installer
3. Wait for "Extracting files" stage.

**Suggested Resolution:**
Check disk space and file size requirements before extracting files.

**Comment by RyanWalpoleEnterprises** [comment]
**Intended Resolution:**
Include failsafe in the extraction process. At point of mod extraction, run:

```
try{
     DriveInfo driveInfo = new DriveInfo(Properties.Settings.Default.StardewDir);
     long Freespace = driveInfo.AvailableFreeSpace / 1024;

     if(FileSize > Freespace) {   //warn user that file space requirements are not met, abort extraction   }
     else{   //go about normal operations   }
```

**Comment by RyanWalpole** [comment]
Will fix this issue for version 220301 😄

**Comment by RyanWalpole** [comment]
**Issue Resolution**

- [x] Check over source code for explanation for issue
- [x] Plan how to resolve this issue in code.
- [ ] Implement resolution
- [ ] Test resolution to best of abilities
*(I don't have any disks close to being full)*
- [ ] Commit changes
- [ ] Pull request and merge

**Comment by RyanWalpole** [comment]
**Fix Testing**
Was able to test to limited ability. Issue seems to be resolved.

**Documentation:**
[Issues: Automatic Modpack Installer - Modpack Installation Failed at "Extracting Files" stage](https://github.com/RyanWalpoleEnterprises/Stardew-Valley-Mod-Manager/wiki/Issues:-Automatic-Modpack-Installer#modpack-installation-failed-at-extracting-files-stage)
_on the SDV Mod Manager Wiki_
