### ISSUE TITLE
[Issue] False positive warning for SMAPI not being installed

### ISSUE THREAD

**Issue by Crutionix** [RyanWalpoleEnterprises/Stardew-Valley-Mod-Manager#7]
**Issue:** 
The application presents a warning banner informing the user that SMAPI is not detected in the Stardew Valley directory even though SMAPI is not only installed in the directory - but in some cases, the warning was not present at an earlier point despite no file changes being made.

**Steps to Replicate:**
1. Have Stardew Valley and SMAPI installed to the same directory.
2. Be (un)lucky enough for it to give the false positive.

**Suggested Resolution:**
Check and adjust the way that the application detects SMAPI being installed.

**Comment by RyanWalpole** [comment]
Currently the code is flawed in that it only fires the warning banner dependent on the file version of the SMAPI executable being fetched. 

```
try 
             {
                var SMAPIVersion = FileVersionInfo.GetVersionInfo(Properties.Settings.Default.StardewDir + 
                @"\StardewModdingAPI.exe");
     
                string SMAPIVersionText = "SMAPI " + "v" + SMAPIVersion.FileVersion;
     
                SMAPIVer.Text = SMAPIVersionText;

                SMAPIWarning.Visible = false;
                SMAPIVer.Visible = true;
             }

catch
            {
                SMAPIVer.Text = "SMAPI Not Installed";
                SMAPIWarning.Visible = true;
                SMAPIVer.Visible = true;
            }
```

If the file version takes too long to be fetched or doesn't get fetched, there's no fail safe for the warning.

**Comment by RyanWalpole** [comment]
**Issue Resolution**

- [ ] Check over source code for explanation for issue
- [ ] Plan how to resolve this issue in code.
- [ ] Implement resolution
- [ ] Test resolution to best of abilities
*(I am yet to experience this false positive)*
- [ ] Commit changes
- [ ] Pull request and merge

**Comment by RyanWalpole** [comment]
**Fix Testing:**
Was able to replicate the issue and have observed that the fix has worked successfully.

**Documentation:**
[Issues: Stardew Valley Mod Manager - SDV Mod Manager says SMAPI is not detected but it is installed.](https://github.com/RyanWalpoleEnterprises/Stardew-Valley-Mod-Manager/issues/7)
_on the SDV Mod Manager Wiki_
